### ISSUE TITLE
SPS GetFeasibility Naming & XmlRootElement Annotation

### ISSUE THREAD

**Issue by jamesgustard** [highsource/ogc-schemas#154]
Hi,
Is there any reason why the  GetFeasibilityType and GetFeasibilityResponseType are named so?

Would it not be more intuitive to call them GetFeasibilityRequest and GetFeasibilityResponse.
Also would it cause a problem to add XmlRootElement annotations to the request/response objects? I have done this myself by changing the binding files, but if it was added as standard it would make integrating the SPS schemas with Java spring web services much easier.

**Comment by highsource** [comment]
They're named so because they're named so in the schema:

* https://github.com/highsource/ogc-schemas/blob/master/schemas/src/main/resources/ogc/sps/1.0.0/spsGetFeasibilityRequest.xsd#L20
* https://github.com/highsource/ogc-schemas/blob/master/schemas/src/main/resources/ogc/sps/2.0/spsGetFeasibility.xsd#L28

No, it should not cause a problem to add the `@XmlRootElement` annotations (can be easily done with `jaxb2-annotate-plugin` or other means). Would you please send a PR for this?
